### ISSUE TITLE
demo code build error

### ISSUE THREAD

**Issue by kainecy** [HMS-Core/hms-3d-modeling-demo-ios#1]
CopyPlistFile /Users/HanHongmin/Library/Developer/Xcode/DerivedData/Modeling3dDemo-hbifhhveiqrejgfirhcdunirjsem/Build/Products/Debug-iphoneos/Modeling3dDemo.app/agconnect-services.plist /Users/HanHongmin/xcodeprojects/hms-3d-modeling-demo-ios/3DModeling-objective-c/Modeling3dDemo/agconnect-services.plist (in target 'Modeling3dDemo' from project 'Modeling3dDemo')
    cd /Users/HanHongmin/xcodeprojects/hms-3d-modeling-demo-ios/3DModeling-objective-c
    builtin-copyPlist --convert binary1 --outdir /Users/HanHongmin/Library/Developer/Xcode/DerivedData/Modeling3dDemo-hbifhhveiqrejgfirhcdunirjsem/Build/Products/Debug-iphoneos/Modeling3dDemo.app -- /Users/HanHongmin/xcodeprojects/hms-3d-modeling-demo-ios/3DModeling-objective-c/Modeling3dDemo/agconnect-services.plist

error: unable to read input file as a property list: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 2.) (in target 'Modeling3dDemo' from project 'Modeling3dDemo')

**Comment by caibobitHuawei** [comment]
You need to create the agconnect-services.plist configuration file on the AGC website and replace the agconnect-services.plist file in the Modeling3dDemo. For details, see the following steps.

Getting Started

Clone the code library to the local computer.

git clone https://github.com/HMS-Core/hms-3d-modeling-demo-ios.git
If you have not registered as a developer, register and create an app in AppGallery Connect.

Obtain the agconnect-services.plist file from Huawei Developers.

Replace the agconnect-services.plist file in Modeling3dDemo of the project.

Compile and run on an IOS device or simulator.

try ~~ Good Luck

**Comment by HongminHan** [comment]
@caibobitHuawei build success, THX
